---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-keepalived
      keepalived_vrrp_instances:
        - name: VI_1
          state: MASTER
          interface: eth0
          unicast_src_ip: "{{ ansible_default_ipv4.address }}"
          secondary_private_ip: "{{ ansible_default_ipv4.address | ipmath(1) }}"
          virtual_router_id: 51
          priority: 255
          authentication:
            auth_type: PASS
            auth_pass: "12345"
          virtual_ipaddresses:
            - name: "{{ ansible_default_ipv4.address | ipmath(1) }}"
              cidr: 24
